service: VerifyAuth


provider:
  name: aws
  profile: tombcf
  runtime: nodejs14.x
  region: eu-west-2
  stage: test
  timeout: 30 # optional, default is 6
  memorySize: 128 #512 default, 1536 is the max-- this also scales processor resources.


package:
  include:
    - src/handler.js


functions:
  cognitoVerifyAuth:
    role: arn:aws:lambda:eu-west-2:444817108422:function:broker_verify_auth
    handler: src/handler.handle
    timeout: 100
    memorySize: 128 #512 default, 1536 is the max-- this also scales processor resources.
    description: "Verify Auth"